trigger:
  branches:
    include:
    - release/*
    - jviau/test-mirror

resources:
  repositories:
  - repository: eng
    type: git
    name: engineering
    ref: refs/heads/jviau/merge-mirror-abort

variables:
  - template: ci/variables/cfs.yml@eng

# force a conflict!
extends:
  template: ci/merge-mirror.yml@eng
